### PR TITLE
Feature improvement

### PR DESCRIPTION
**Pull request by mscheepers**
added support of additional mstest command line options

### CODE REVIEW

**Comment by mrjackdavis** [comment]
@mscheepers wow, you've done a fair amount of work. Thanks :+1:

Sadly there's no tests for this repo so its hard for me to know it's working as expected. Nevertheless it looks good at face value.

I'm not going to have a chance to actually test this; with your word though, I'm happy to merge it. Are there any breaking changes?

**Comment by msperceptive** [comment]
@mrjackdavis thanks... ;)

I'm not aware of any breaking changes. The deprecated `mstestPath` is still evaluated if it is specifed.

The minimum required configuration is the source (as was previously) and for all other introduced options I think I choose usefull defaults or I took over your defaults .

The "unpublished" version of this script is currently already in use for some four projects.

But, before you merge this, I just realized that I didn't adapt the README documentation. So I will update and commit that also, so that others are informed about the new configuration options.

**Comment by mscheepers** [comment]
@mrjackdavis thanks... ;)

I'm not aware of any breaking changes. The deprecated mstestPath is still evaluated if it is specifed.

The minimum required configuration is the source (as was previously) and for all other introduced options I think I choose usefull defaults or I took over your defaults .

The "unpublished" version of this script is already in use for some four projects.

But, before you merge this, I just realized that I didn't adapt the README documentation. So I will update and commit that also, so that others are informed about the new configuration options.

**Comment by mscheepers** [comment]
@mrjackdavis well, I'm done with the documentation too.

**Comment by mscheepers** [comment]
@mrjackdavis and finally removed the obsoleted code... :)

**Pull request merged**
